### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GregorTV7** [0x77ff/Roblox-Token-Hacks#2]
Response text: {"errors":[{"code":0,"message":"Unauthorized"}]}
GET request failed with status code 401
Response text: {"errors":[{"code":0,"message":"NotFound"}]}
GET request failed with status code 404
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]
errors : [{'code': 0, 'message': 'Unauthorized'}]

**Comment by 0x77ff** [comment]
Your cookie expired, get a new one
